
// IS THE PILOT'S GAP TO MODE 10 ITS FORECAST, OR ITS STRUCTURE? — the measurement that
// should have come before any of §46's forecast work (the owner: get the pilot to equal
// or exceed 10).
//
// 10 reaches 44-51x on a compiled program where the pilot's composition reads single
// digits, and every route tried so far has assumed the difference is FORECAST QUALITY.
// This tests that assumption directly by handing the pilot the best forecast its own
// model class can possibly have: its readouts refitted IN-SAMPLE on the target program's
// own open-loop record, through its own row builder, leads, window, ridge and column
// scaling. Nothing is left to improve about the prediction — it is fitted on the very
// data it will be scored against, which is a CEILING and not a proposal (the project's
// own self-fit idiom, as with the corner banks' 3.27x).
//
// READ IT AS A FORK. If the self-fit ceiling approaches 10's level, forecast quality is
// the whole gap and the work is to find a cheap forecast that good. If it stalls near
// where the shipped pilot already is, then NO forecast improvement can close the gap and
// the difference is structural — 10 inverts the plant over the WHOLE program with a
// non-causal deconvolution, where the pilot must act causally from a finite preview, and
// that is not a modelling deficit at all.
//
// THE CONFOUND. `test/_twinreduced.mjs` beat the pilot's forecast everywhere (sharp elbow
// 0.402 -> 0.951) but changed TWO things at once: it trained on TWIN data instead of
// machine data, AND it used a 768-sample log-spaced window instead of the pilot's own.
// Attribution between them was never measured, and the 3.5x that followed was a forecast
// BOUND projection rather than a delivered result.
//
// THIS ISOLATES THE DATA. The pilot is commissioned normally; then its readout weights
// are REFITTED, through the pilot's OWN `_row` builder, at its OWN leads and window, on
// records generated by the TWIN over open wanders. One variable: where the training rows
// came from. Then both are deployed on the true machine and scored — the same QP, the
// same cadence, the same everything else.
//
// If the refit wins, the twin's gift is the DATA (unlimited, chosen excitation, open
// paths that cannot alias) and it plugs into the shipped controller unchanged. If it does
// not, the long window was doing the work in the earlier bench and the pilot needs the
// window, not the data.
import { solveRidge } from '/home/user/Tisaic.github.io/lib/pilot/pilot.js';
import { PG, commissionArm, deployOn, makeArm, mkPath, homeArm, routeSignals }
  from '/home/user/Tisaic.github.io/test/pilot/rigs/arm-rig.mjs';
import { randomWander } from '/home/user/Tisaic.github.io/lib/flexisim/demopath.js';

const SS_UNUSED = 0;
const TWIN_FIT = { K: 0.9993, E: 0.05997, damp: 3.00e-3, bl: 6.08e-5 };
const mkRnd = (s) => { let z = s >>> 0; return () => (z = (z * 1664525 + 1013904223) >>> 0) / 4294967296; };

console.log(`arm: K ${PG.K} / E ${PG.E}; twin at its LM fit ${JSON.stringify(TWIN_FIT)}`);
const pilot = await commissionArm({ seed: 1, train: { shape: 'rounded', feed: 0.004 } });
if (!pilot) { console.log('commissioning never terminated'); process.exit(1); }
console.log(`commissioned: ${pilot.verdict.deploy ? 'deploy' : 'REFUSED'}; sample ${pilot.sample}, N ${pilot.N}`);

// record the TWIN over open wanders, in the pilot's own signal routing and cadence
const recordOn = async (params, path) => {
  const m = await makeArm(params);
  homeArm(m.arm, m.servo, path);
  const S = pilot.sample, x = [], cmd = [], e = [];
  const total = Math.ceil(path.lap);
  for (let k = 0; k < total; k++) {
    const c = path.at(k);
    const [q1, q2] = m.arm.ik(c.x, c.y, true);
    const rt = m.arm.ikRates(q1, q2, c.vx, c.vy, c.ax, c.ay);
    const tau = m.servo.torques([{ theta: q1, omega: rt.dq[0], alpha: rt.ddq[0] },
      { theta: q2, omega: rt.dq[1], alpha: rt.ddq[1] }]);
    m.arm.step(tau[0], tau[1], 1);
    if (k % S === 0) {
      const r = routeSignals(m.arm, [{ pos: q1 }, { pos: q2 }], tau);
      x.push(r.measured); cmd.push([q1, q2]); e.push(r.truth);
    }
  }
  await m.arm.l1.destroy(); await m.arm.l2.destroy();
  return { x, cmd, u: [], e };
};

// the record is the TARGET PROGRAM ITSELF, open loop on the TRUE machine — in-sample by
// construction, which is the point: this is a ceiling, not a deployable fit.
const SHAPES = (process.env.CEIL_SHAPES || 'rounded,circle,sharp').split(',');
const recordTrue = async (path) => recordOn(undefined, path);

// For each program: refit IN-SAMPLE on that program, deploy, restore, deploy the shipped
// weights as the control. One variable per row: what the readouts were fitted on.
const saved = pilot.readouts.map((ro) => ro.w.map((w) => w.slice()));
const restore = () => { for (let c = 0; c < pilot.readouts.length; c++) pilot.readouts[c].w = saved[c].map((w) => w.slice()); };

const refitOn = (recs) => {
  for (let c = 0; c < pilot.readouts.length; c++) {
    const ro = pilot.readouts[c];
    for (let li = 0; li < ro.w.length; li++) {
      const L = ro.leads[Math.min(li, ro.leads.length - 1)];
      const back = Math.max((ro.mLag - 1) * ro.stride, (ro.fLag - 1) * ro.stride - L);
      const rows = [], ys = [];
      const keep = pilot._rec;
      for (const rec of recs) {
        pilot._rec = rec;
        for (let k = back; k < rec.e.length - L - 1; k++) {
          rows.push(pilot._row(c, k, L, ro.stride, ro.poly, ro.mLag, ro.fLag, ro.sched));
          ys.push(rec.e[k + L][c]);
        }
      }
      pilot._rec = keep;
      if (rows.length < ro.w[li].length * 3) continue;
      // the readout's OWN ridge and column scaling — substituting my own re-regularises
      // the inverse the QP depends on, measured at 0.65x/0.54x when I did exactly that
      ro.w[li] = solveRidge(rows, ys, ro.ridge, pilot._colScale(rows[0]));
    }
  }
};

console.log('\n  program        shipped      self-fit ceiling    ratio   (open loop)');
for (const shape of SHAPES) {
  const path = mkPath(shape, 0.004);
  restore();
  const base = (await deployOn(pilot, shape, true, 0.004)).r.totalRms;
  const off = (await deployOn(pilot, shape, false, 0.004)).r.totalRms;
  const rec = await recordOn(undefined, path);
  refitOn([rec]);
  const ceil = (await deployOn(pilot, shape, true, 0.004)).r.totalRms;
  restore();
  console.log(`  ${shape.padEnd(14)} ${base.toExponential(3).padStart(10)}`
    + ` ${ceil.toExponential(3).padStart(17)} ${(base / ceil).toFixed(2).padStart(8)}x`
    + `   ${off.toExponential(3)}  (shipped ${(off / base).toFixed(1)}x, ceiling ${(off / ceil).toFixed(1)}x over open)`);
}
console.log('EXIT 0');
