
// DOES THE TWIN-TRAINED FORECAST DELIVER? — turning §46's projection into a number the
// machine produced (rule 16), and resolving a confound in my own earlier bench.
//
// THE CONFOUND. `test/_twinreduced.mjs` beat the pilot's forecast everywhere (sharp elbow
// 0.402 -> 0.951) but changed TWO things at once: it trained on TWIN data instead of
// machine data, AND it used a 768-sample log-spaced window instead of the pilot's own.
// Attribution between them was never measured, and the 3.5x that followed was a forecast
// BOUND projection rather than a delivered result.
//
// THIS ISOLATES THE DATA. The pilot is commissioned normally; then its readout weights
// are REFITTED, through the pilot's OWN `_row` builder, at its OWN leads and window, on
// records generated by the TWIN over open wanders. One variable: where the training rows
// came from. Then both are deployed on the true machine and scored — the same QP, the
// same cadence, the same everything else.
//
// If the refit wins, the twin's gift is the DATA (unlimited, chosen excitation, open
// paths that cannot alias) and it plugs into the shipped controller unchanged. If it does
// not, the long window was doing the work in the earlier bench and the pilot needs the
// window, not the data.
import { solveRidge } from '/home/user/Tisaic.github.io/lib/pilot/pilot.js';
import { PG, commissionArm, deployOn, makeArm, mkPath, homeArm, routeSignals }
  from '/home/user/Tisaic.github.io/test/pilot/rigs/arm-rig.mjs';
import { randomWander } from '/home/user/Tisaic.github.io/lib/flexisim/demopath.js';

const SS_UNUSED = 0;
const TWIN_FIT = { K: 0.9993, E: 0.05997, damp: 3.00e-3, bl: 6.08e-5 };
const mkRnd = (s) => { let z = s >>> 0; return () => (z = (z * 1664525 + 1013904223) >>> 0) / 4294967296; };

console.log(`arm: K ${PG.K} / E ${PG.E}; twin at its LM fit ${JSON.stringify(TWIN_FIT)}`);
const pilot = await commissionArm({ seed: 1, train: { shape: 'rounded', feed: 0.004 } });
if (!pilot) { console.log('commissioning never terminated'); process.exit(1); }
console.log(`commissioned: ${pilot.verdict.deploy ? 'deploy' : 'REFUSED'}; sample ${pilot.sample}, N ${pilot.N}`);

// record the TWIN over open wanders, in the pilot's own signal routing and cadence
const recordTwin = async (path) => {
  const m = await makeArm(TWIN_FIT);
  homeArm(m.arm, m.servo, path);
  const S = pilot.sample, x = [], cmd = [], e = [];
  const total = Math.ceil(path.lap);
  for (let k = 0; k < total; k++) {
    const c = path.at(k);
    const [q1, q2] = m.arm.ik(c.x, c.y, true);
    const rt = m.arm.ikRates(q1, q2, c.vx, c.vy, c.ax, c.ay);
    const tau = m.servo.torques([{ theta: q1, omega: rt.dq[0], alpha: rt.ddq[0] },
      { theta: q2, omega: rt.dq[1], alpha: rt.ddq[1] }]);
    m.arm.step(tau[0], tau[1], 1);
    if (k % S === 0) {
      const r = routeSignals(m.arm, [{ pos: q1 }, { pos: q2 }], tau);
      x.push(r.measured); cmd.push([q1, q2]); e.push(r.truth);
    }
  }
  await m.arm.l1.destroy(); await m.arm.l2.destroy();
  return { x, cmd, u: [], e };
};

const NW = +(process.env.REFIT_W || 4);
console.log(`generating ${NW} twin wanders at the pilot's cadence…`);
const recs = [];
for (let i = 0; i < NW; i++) {
  recs.push(await recordTwin(randomWander(mkRnd(3000 + i), 0.004, { centre: PG.centre, reach: 6 })));
  console.log(`  wander ${i + 1}: ${recs.at(-1).e.length} samples`);
}

// REFIT every readout weight vector through the pilot's OWN row builder
const saved = pilot.readouts.map((ro) => ro.w.map((w) => w.slice()));
console.log('refitting the readouts on twin data (same rows, same leads, same window)…');
for (let c = 0; c < pilot.readouts.length; c++) {
  const ro = pilot.readouts[c];
  for (let li = 0; li < ro.w.length; li++) {
    const L = ro.leads[Math.min(li, ro.leads.length - 1)];
    const back = Math.max((ro.mLag - 1) * ro.stride, (ro.fLag - 1) * ro.stride - L);
    const rows = [], ys = [];
    const keep = pilot._rec;
    for (const rec of recs) {
      pilot._rec = rec;
      for (let k = back; k < rec.e.length - L - 1; k++) {
        rows.push(pilot._row(c, k, L, ro.stride, ro.poly, ro.mLag, ro.fLag, ro.sched));
        ys.push(rec.e[k + L][c]);
      }
    }
    pilot._rec = keep;
    if (rows.length < ro.w[li].length * 3) { console.log(`  ch${c} lead ${li}: too few rows, kept`); continue; }
    ro.w[li] = solveRidge(rows, ys, 1e-6);
    if (li === 0) console.log(`  ch${c}: ${rows.length} twin rows x ${ro.w[li].length} terms`);
  }
}

// SCORE BOTH ON THE TRUE MACHINE, same QP, same cadence
const score = async (label) => {
  const out = {};
  for (const shape of ['rounded', 'circle', 'sharp']) {
    const on = await deployOn(pilot, shape, true, 0.004);
    // TOTAL, not contour: the Path tab's own doctrine is that lag is a defect too and
    // the score is their sum — a rung must not buy one with the other unseen (rule 6).
    out[shape] = on.r.totalRms;
  }
  console.log(`${label}: ` + Object.entries(out).map(([k, v]) => `${k} ${(+v).toExponential(3)}`).join('  '));
  return out;
};
const twinFitted = await score('twin-refitted ');
for (let c = 0; c < pilot.readouts.length; c++) pilot.readouts[c].w = saved[c];
const machineFitted = await score('machine-fitted');
console.log('\n  program        machine-fitted   twin-refitted    ratio');
for (const s of ['rounded', 'circle', 'sharp']) {
  console.log(`  ${s.padEnd(14)} ${(+machineFitted[s]).toExponential(3).padStart(14)}`
    + ` ${(+twinFitted[s]).toExponential(3).padStart(15)}`
    + ` ${(machineFitted[s] / twinFitted[s]).toFixed(2).padStart(8)}x`);
}
console.log('EXIT 0');
