% Compute power spectrum of data set

% Generated by MATLAB(R) 9.8 and Signal Processing Toolbox 8.4.
% Generated on: 24-Sep-2021 14:11:46

function input_spectrum(u1, u2, u3, u4, u5, u6)

% Parameters
timeLimits = seconds([0 900.1]); % seconds
frequencyLimits = [0 1.6]; % Hz

figure
hold on

n_reduce = 2;
FrequencyResolution = 0.01;

%%
% Index into signal time region of interest
u1_unnamed_ROI = squeeze(u1.Data(1:n_reduce:end));
timeValues = u1.Time(1:n_reduce:end);
u1_unnamed_ROI = timetable(seconds(timeValues(:)),u1_unnamed_ROI,'VariableNames',{'Data'});
u1_unnamed_ROI = u1_unnamed_ROI(timerange(timeLimits(1),timeLimits(2),'closed'),1);

% Compute spectral estimate
% Run the function call below without output arguments to plot the results
[pxx,freq] = pspectrum(u1_unnamed_ROI, ...
    'FrequencyLimits',frequencyLimits,'FrequencyResolution',FrequencyResolution);

p_db = pow2db(pxx);
freq = freq(1:n_reduce:end);
p_db = p_db(1:n_reduce:end);
plot(freq, p_db)

%%
% Index into signal time region of interest
u2_unnamed_ROI = squeeze(u2.Data(1:n_reduce:end));
timeValues = u2.Time(1:n_reduce:end);
u2_unnamed_ROI = timetable(seconds(timeValues(:)),u2_unnamed_ROI,'VariableNames',{'Data'});
u2_unnamed_ROI = u2_unnamed_ROI(timerange(timeLimits(1),timeLimits(2),'closed'),1);

% Compute spectral estimate
% Run the function call below without output arguments to plot the results
[pxx,freq] = pspectrum(u2_unnamed_ROI, ...
    'FrequencyLimits',frequencyLimits,'FrequencyResolution',FrequencyResolution);


p_db = pow2db(pxx);
freq = freq(1:n_reduce:end);
p_db = p_db(1:n_reduce:end);
plot(freq, p_db)

%%
% Index into signal time region of interest
u3_unnamed_ROI = squeeze(u3.Data(1:n_reduce:end));
timeValues = u3.Time(1:n_reduce:end);
u3_unnamed_ROI = timetable(seconds(timeValues(:)),u3_unnamed_ROI,'VariableNames',{'Data'});
u3_unnamed_ROI = u3_unnamed_ROI(timerange(timeLimits(1),timeLimits(2),'closed'),1);

% Compute spectral estimate
% Run the function call below without output arguments to plot the results
[pxx,freq] = pspectrum(u3_unnamed_ROI, ...
    'FrequencyLimits',frequencyLimits,'FrequencyResolution',FrequencyResolution);

p_db = pow2db(pxx);
freq = freq(1:n_reduce:end);
p_db = p_db(1:n_reduce:end);
plot(freq, p_db)

%%
% Index into signal time region of interest
u4_unnamed_ROI = squeeze(u4.Data(1:n_reduce:end));
timeValues = u4.Time(1:n_reduce:end);
u4_unnamed_ROI = timetable(seconds(timeValues(:)),u4_unnamed_ROI,'VariableNames',{'Data'});
u4_unnamed_ROI = u4_unnamed_ROI(timerange(timeLimits(1),timeLimits(2),'closed'),1);

% Compute spectral estimate
% Run the function call below without output arguments to plot the results
[pxx,freq] = pspectrum(u4_unnamed_ROI, ...
    'FrequencyLimits',frequencyLimits,'FrequencyResolution',FrequencyResolution);

p_db = pow2db(pxx);
freq = freq(1:n_reduce:end);
p_db = p_db(1:n_reduce:end);
plot(freq, p_db)

%%
% Index into signal time region of interest
u5_unnamed_ROI = squeeze(u5.Data(1:n_reduce:end));
timeValues = u5.Time(1:n_reduce:end);
u5_unnamed_ROI = timetable(seconds(timeValues(:)),u5_unnamed_ROI,'VariableNames',{'Data'});
u5_unnamed_ROI = u5_unnamed_ROI(timerange(timeLimits(1),timeLimits(2),'closed'),1);

% Compute spectral estimate
% Run the function call below without output arguments to plot the results
[pxx,freq] = pspectrum(u5_unnamed_ROI, ...
    'FrequencyLimits',frequencyLimits,'FrequencyResolution',FrequencyResolution);

p_db = pow2db(pxx);
freq = freq(1:n_reduce:end);
p_db = p_db(1:n_reduce:end);
plot(freq, p_db)

%%
% Index into signal time region of interest
u6_unnamed_ROI = squeeze(u6.Data(1:n_reduce:end));
timeValues = u6.Time(1:n_reduce:end);
u6_unnamed_ROI = timetable(seconds(timeValues(:)),u6_unnamed_ROI,'VariableNames',{'Data'});
u6_unnamed_ROI = u6_unnamed_ROI(timerange(timeLimits(1),timeLimits(2),'closed'),1);

% Compute spectral estimate
% Run the function call below without output arguments to plot the results
[pxx,freq] = pspectrum(u6_unnamed_ROI, ...
    'FrequencyLimits',frequencyLimits,'FrequencyResolution',FrequencyResolution);

p_db = pow2db(pxx);
freq = freq(1:n_reduce:end);
p_db = p_db(1:n_reduce:end);
plot(freq, p_db)

title('')
grid on
ylabel('Power Spectrum (dB)')
xlabel('Freqency (Hz)')

end