% Compute power spectrum of data set

% Generated by MATLAB(R) 9.8 and Signal Processing Toolbox 8.4.
% Generated on: 24-Sep-2021 14:18:57

function output_spectrum(q1, q2, q3, q4, q5, q6)

% Parameters
timeLimits = seconds([0 900.1]); % seconds
frequencyLimits = [0 1.6]; % Hz

figure
hold on

n_reduce = 2;
FrequencyResolution = 0.01;

%%
% Index into signal time region of interest
q1_unnamed_ROI = squeeze(q1.Data(1:n_reduce:end));
timeValues = q1.Time(1:n_reduce:end);
q1_unnamed_ROI = timetable(seconds(timeValues(:)),q1_unnamed_ROI,'VariableNames',{'Data'});
q1_unnamed_ROI = q1_unnamed_ROI(timerange(timeLimits(1),timeLimits(2),'closed'),1);

% Compute spectral estimate
% Run the function call below without output arguments to plot the results
[pxx,freq] = pspectrum(q1_unnamed_ROI, ...
    'FrequencyLimits',frequencyLimits,'FrequencyResolution',FrequencyResolution);

p_db = pow2db(pxx);
freq = freq(1:n_reduce:end);
p_db = p_db(1:n_reduce:end);
plot(freq, p_db)

%%
% Index into signal time region of interest
q2_unnamed_ROI = squeeze(q2.Data(1:n_reduce:end));
timeValues = q2.Time(1:n_reduce:end);
q2_unnamed_ROI = timetable(seconds(timeValues(:)),q2_unnamed_ROI,'VariableNames',{'Data'});
q2_unnamed_ROI = q2_unnamed_ROI(timerange(timeLimits(1),timeLimits(2),'closed'),1);

% Compute spectral estimate
% Run the function call below without output arguments to plot the results
[pxx,freq] = pspectrum(q2_unnamed_ROI, ...
    'FrequencyLimits',frequencyLimits,'FrequencyResolution',FrequencyResolution);

p_db = pow2db(pxx);
freq = freq(1:n_reduce:end);
p_db = p_db(1:n_reduce:end);
plot(freq, p_db)

%%
% Index into signal time region of interest
q3_unnamed_ROI = squeeze(q3.Data(1:n_reduce:end));
timeValues = q3.Time(1:n_reduce:end);
q3_unnamed_ROI = timetable(seconds(timeValues(:)),q3_unnamed_ROI,'VariableNames',{'Data'});
q3_unnamed_ROI = q3_unnamed_ROI(timerange(timeLimits(1),timeLimits(2),'closed'),1);

% Compute spectral estimate
% Run the function call below without output arguments to plot the results
[pxx,freq] = pspectrum(q3_unnamed_ROI, ...
    'FrequencyLimits',frequencyLimits,'FrequencyResolution',FrequencyResolution);

p_db = pow2db(pxx);
freq = freq(1:n_reduce:end);
p_db = p_db(1:n_reduce:end);
plot(freq, p_db)

%%
% Index into signal time region of interest
q4_unnamed_ROI = squeeze(q4.Data(1:n_reduce:end));
timeValues = q4.Time(1:n_reduce:end);
q4_unnamed_ROI = timetable(seconds(timeValues(:)),q4_unnamed_ROI,'VariableNames',{'Data'});
q4_unnamed_ROI = q4_unnamed_ROI(timerange(timeLimits(1),timeLimits(2),'closed'),1);

% Compute spectral estimate
% Run the function call below without output arguments to plot the results
[pxx,freq] = pspectrum(q4_unnamed_ROI, ...
    'FrequencyLimits',frequencyLimits,'FrequencyResolution',FrequencyResolution);

p_db = pow2db(pxx);
freq = freq(1:n_reduce:end);
p_db = p_db(1:n_reduce:end);
plot(freq, p_db)

%%
% Index into signal time region of interest
q5_unnamed_ROI = squeeze(q5.Data(1:n_reduce:end));
timeValues = q5.Time(1:n_reduce:end);
q5_unnamed_ROI = timetable(seconds(timeValues(:)),q5_unnamed_ROI,'VariableNames',{'Data'});
q5_unnamed_ROI = q5_unnamed_ROI(timerange(timeLimits(1),timeLimits(2),'closed'),1);

% Compute spectral estimate
% Run the function call below without output arguments to plot the results
[pxx,freq] = pspectrum(q5_unnamed_ROI, ...
    'FrequencyLimits',frequencyLimits,'FrequencyResolution',FrequencyResolution);

p_db = pow2db(pxx);
freq = freq(1:n_reduce:end);
p_db = p_db(1:n_reduce:end);
plot(freq, p_db)

%%
% Index into signal time region of interest
q6_unnamed_ROI = squeeze(q6.Data(1:n_reduce:end));
timeValues = q6.Time(1:n_reduce:end);
q6_unnamed_ROI = timetable(seconds(timeValues(:)),q6_unnamed_ROI,'VariableNames',{'Data'});
q6_unnamed_ROI = q6_unnamed_ROI(timerange(timeLimits(1),timeLimits(2),'closed'),1);

% Compute spectral estimate
% Run the function call below without output arguments to plot the results
[pxx,freq] = pspectrum(q6_unnamed_ROI, ...
    'FrequencyLimits',frequencyLimits,'FrequencyResolution',FrequencyResolution);

p_db = pow2db(pxx);
freq = freq(1:n_reduce:end);
p_db = p_db(1:n_reduce:end);
plot(freq, p_db)

title('')
grid on
ylabel('Power Spectrum (dB)')
xlabel('Freqency (Hz)')

end